import { Banner1 } from "./res/Images/image"

export const homeProductdata = [
    {
        homeimg:Banner1,
        homename:"SleutelhangersSleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    },
    {
        homeimg:Banner1,
        homename:"Sleutelhangers",
    }
]